# Book settings
title: 2020 MATH 200 Section 102
author: J. Colliander
logo: logo.png

latex:
  latex_documents:
    targetname: 2020math200section102.tex
launch_buttons:
  jupyterhub_url: "https://ubc.syzygy.ca"  # The URL for your BinderHub (e.g., https://mybinder.org)


