# Book settings
title: 2020 MATH 200 Section 102
author: J. Colliander
logo: logo.png

latex:
  latex_documents:
    targetname: 2020math200section102.tex
# Information about where the book exists on the web
repository:
  url                       : https://github.com/colliand/2020math220section102  # Online location of your book
#  path_to_book              : path/to/book  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  jupyterhub_url: "https://ubc.syzygy.ca/jupyter/"  # The URL for your BinderHub (e.g., https://mybinder.org)
  binderhub_url: 
  colab_url:


